In [45]:
import time
import numpy as np

In [46]:
pesos_dos_objetos = np.array([350, 250, 160, 120, 200, 100, 120, 220, 40, 80, 100, 300, 180, 250, 220, 150, 280, 310, 120, 160, 110, 210])
valor_dos_objetos = np.array([300, 400, 450, 350, 250, 300, 200, 250, 150, 400, 350, 300, 450, 500, 350, 400, 200, 300, 250, 300, 150, 200])

In [47]:
PESO_MAX = 3000
tamanho_da_populacao = 10
tamanho_do_genoma = np.size(pesos_dos_objetos)
taxa_de_mutacao = 0.05

print(f"tamanho da populacao: {tamanho_da_populacao}")
print(f"tamanho do genoma: {tamanho_do_genoma}")
print(f"taxa de mutacao: {taxa_de_mutacao}")
print(f"peso maximo: {PESO_MAX}")

tamanho da populacao: 10
tamanho do genoma: 22
taxa de mutacao: 0.05
peso maximo: 3000


In [48]:
def gera_populacao(tamanho_da_populacao, tamanho_do_genoma):
    return np.random.randint(2, size=(tamanho_da_populacao, tamanho_do_genoma))

In [49]:
def fitness(populacao):
    pesos = np.dot(populacao, pesos_dos_objetos)
    soma_dos_pesos = np.sum(pesos)
    compare = np.logical_not(pesos > np.full_like(np.shape(pesos), PESO_MAX))
    #print((compare))

    valores = np.dot(populacao, valor_dos_objetos)
    valores = compare * valores
    soma_dos_valores = np.sum(valores)
    valor_max = np.max(valores)

    return pesos, valores

In [ ]:
inicio= time.time()

populacao = gera_populacao(tamanho_da_populacao, tamanho_do_genoma)

fit_score = fitness(populacao)

print(f"População inicial: {populacao}")
print(f"Fitness inicial: {fit_score}")

ponto_de_crossover = np.random.randint(tamanho_do_genoma - 1)

fim = time.time()
delta = fim - inicio

print(f"{delta} segundos")

População inicial: [[1 0 0 1 0 0 0 0 1 1 0 1 0 1 1 0 0 1 0 0 1 1]
 [0 0 1 0 1 0 1 1 1 0 1 1 1 0 1 0 1 1 1 1 1 1]
 [1 1 1 1 0 0 1 0 1 0 0 0 1 1 0 1 0 0 0 1 1 0]
 [0 0 1 0 0 0 0 1 0 0 1 0 1 0 0 1 1 1 0 0 1 0]
 [1 0 1 1 1 1 0 0 0 1 1 1 0 0 0 0 1 1 0 0 0 0]
 [1 1 1 1 1 0 1 0 1 0 0 1 1 1 1 1 1 1 0 1 1 0]
 [1 1 1 1 1 1 1 1 1 1 0 1 0 1 1 1 1 0 1 1 0 0]
 [0 0 1 0 0 1 0 0 1 1 0 1 1 1 1 1 0 1 0 1 0 0]
 [1 0 0 1 1 0 1 0 1 0 1 0 0 0 1 0 1 1 1 1 1 0]
 [1 1 0 0 1 0 0 0 0 0 1 1 1 0 1 0 0 0 1 0 0 1]]
Fitness inicial: (array([1990, 2730, 1890, 1510, 2000, 3200, 3120, 1950, 2130, 1930]), array([3000, 4150, 3650, 2550, 3200,    0,    0, 3900, 3150, 2850]))
0.0036668777465820312 segundos
